In [1]:
!pip3 install memory_profiler
%load_ext memory_profiler

In [2]:
import LaBSE
import numpy as np

In [3]:
labse = LaBSE.LabseSentenceEncoding()

is not trainable


In [4]:
english_sentences = ["dog", "Puppies are nice.", "I enjoy taking long walks along the beach with my dog."]
italian_sentences = ["cane", "I cuccioli sono carini.", "Mi piace fare lunghe passeggiate lungo la spiaggia con il mio cane."]
japanese_sentences = ["犬", "子犬はいいです", "私は犬と一緒にビーチを散歩するのが好きです"]
german_sentences = ["Hund","Welpen sind süß.", "I genieße lange Spaziergänge mit meinem Hund am Strand."]

In [5]:
%%timeit
labse.encode(["This is a longer test sentence to meaure how long the encoding takes."])

107 ms ± 1.51 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [6]:
%%memit
labse.encode(["This is a longer test sentence to meaure how long the encoding takes."])

peak memory: 2690.86 MiB, increment: 36.56 MiB


In [7]:
%mprun -f labse.encode labse.encode(["This is a longer test sentence to meaure how long the encoding takes."])

In [8]:
english_embeddings = labse.encode(english_sentences)
italian_embeddings = labse.encode(italian_sentences)
japanese_embeddings = labse.encode(japanese_sentences)
german_embeddings = labse.encode(german_sentences)

In [9]:
# English-Italian similarity
print (np.matmul(english_embeddings, np.transpose(italian_embeddings)))

# English-Japanese similarity
print (np.matmul(english_embeddings, np.transpose(japanese_embeddings)))

# Italian-Japanese similarity
print (np.matmul(italian_embeddings, np.transpose(japanese_embeddings)))

# German-Japanese similarity
print (np.matmul(german_embeddings, np.transpose(japanese_embeddings)))

# German-English similarity
print (np.matmul(german_embeddings, np.transpose(english_embeddings)))

# German-German similarity
print (np.matmul(german_embeddings, np.transpose(german_embeddings)))

[[0.63192904 0.30619794 0.4429747 ]
 [0.11652699 0.8596665  0.35940558]
 [0.14803992 0.32447973 0.9542651 ]]
[[0.9356719  0.54030657 0.467923  ]
 [0.31804195 0.76222515 0.36085895]
 [0.36750704 0.4279153  0.81714547]]
[[0.53437203 0.25018612 0.19974717]
 [0.30140814 0.71333206 0.40647542]
 [0.38503075 0.47767872 0.86743   ]]
[[0.9462711  0.5427998  0.451137  ]
 [0.38075304 0.7742229  0.5003885 ]
 [0.39104548 0.48709273 0.83822393]]
[[0.92966205 0.34716153 0.39702922]
 [0.41559264 0.8498492  0.37241483]
 [0.44947135 0.3624616  0.94378114]]
[[1.         0.3964759  0.43589252]
 [0.3964759  0.9999998  0.4599799 ]
 [0.43589252 0.4599799  0.9999999 ]]


In [16]:
test_sentences = ["My name is Oliver","call me Oliver", "Mein Name ist Oliver","Ich heiße Oliver", "I am Oliver"]
test_embeddings = labse.encode(test_sentences)
print (np.matmul(test_embeddings, np.transpose(test_embeddings)))

[[1.0000001  0.8645722  0.9723238  0.9550148  0.9220525 ]
 [0.8645722  1.0000004  0.8424641  0.8621087  0.80655986]
 [0.9723238  0.8424641  0.99999976 0.9767357  0.9049208 ]
 [0.9550148  0.8621087  0.9767357  1.0000002  0.92511165]
 [0.9220525  0.80655986 0.9049208  0.92511165 1.        ]]
